### PR TITLE
v13

### PR DESCRIPTION
**Pull request by tptee**
Reworking the architecture and cleaning up cruft to make contributions and compatibility easier. Also trying to batch together some breaking changes and fix some long-standing issues in the process.

- [x] Fix `flow-type` usage and project's Flow annotations
- [x] Reorganize directory structure
- [x] Change the API to a factory that returns preconfigured reducer, middleware, and enhancer
- [x] Remove all control of the reducer from the store enhancer (easier compatibility with `redux-loop`, `immutable`, other community libraries)
- [x] Add public action creators for navigation (finally!)
- [x] Move `<Link>` logic to respective action creators ( in support of #99)
- [x] Clean up old `history@v3` type declarations
- [x] Strip the basename from the initial pathname
- [x] Fix query issues introduced in `v12` (#121 , #127)
- [x] Update documentation
- [x] Remove `<AbsoluteFragment>`
- [x] Update demo

### CODE REVIEW

**Comment by tptee** [comment]
This is a big one, but I'm trying to keep the commit history as clear/atomic as possible. I think an alpha release would be useful as well.

**Comment by divmain** [comment]
@tptee, can you ping me when this is ready for review?

**Comment by csillag** [comment]
So.... Currently, the readme on the master branch [says](https://github.com/FormidableLabs/redux-little-router#stability) this:

> We consider `redux-little-router` to be **stable**. Any API changes will be incremental.

I guess this PR means that this statement is no longer describing your current thinking?
Does this mean that I should wait a bit more, before trying to integrate this router into my app?

**Comment by tptee** [comment]
@csillag, most of these changes are internal. The two breaking changes are 1) the function signature of the router "factory" and 2) the removal of the deprecated `<AbsoluteFragment>`. The first is a tiny boilerplate change, and few people use `<AbsoluteFragment>` anymore.

I think this is firmly in the spirit of "any API changes will be incremental." I wouldn't expect a large migration from the current version!

**Comment by tptee** [comment]
This should be ready to go! The "files changed" diff view is pretty useless because of the `flow-typed` additions, the per-commit diffs will be clearer.

@divmain @baer @alexlande @aweary

**Comment by thj-dk** [comment]
When can we expect to see this merged into master? Can't wait :-)

**Comment by dpoineau** [comment]
@tptee Is there any way with this version to get the exact-matching behavior that AbsoluteFragment previously provided?

**Comment by csillag** [comment]
Am I right to assume that this PR needs to be merged first, before any of the other pending features?

**Comment by jerrymao15** [comment]
@dpoineau My solution in mimicking the behavior of `AbsoluteFragment` was to make a HOF that takes in an absolute route in order to use with the `withConditions` prop available in the `Fragment` component. 

```
const absRoute = abs => ({ route }) => route === abs;

<Fragment forRoute="/" withConditions={absRoute('/home')}>
```

If anyone else has a different way of approaching this let me know!

**Comment by adregan** [comment]
Any way folks can pitch in to get this one moving?

**Comment by cafreeman** [comment]
Ditto what @adregan said. There are a number of fixes in this upcoming release that I'd love to use. Any way I can help out?

**Comment by tptee** [comment]
Prerelease of this at `v13.0.0-0`/`next`!

**Pull request merged**
