### PR TITLE
immutable js integration close #77

### LINKED ISSUE #77: Immutablejs compatibility
Hello, I like the approach you take with this router :)
Do you plan on implementing immutablejs compatibility ?

I made it work in my project by patching store-enhancer.js in my project (using set/get/delete instead of _extends({},...)
https://gist.github.com/Nihaux/0ac0d5e4e7bdc82be78bcb83cbc2fd9e

What do you think would be the best approach to implement this behaviour ? I could work on the PR if needed.

thx

### PR DESCRIPTION
**Pull request by Nihaux**
So I tried to solve the immutable integration #77 using a decorator function. (cf tests)
Works with redux-immutable and redux-immutablejs but redux-immutable still gives a warning in dev mod as he does not know the router key.
Haven't tested on my project yet, just made some unit test. Will do that tomorrow.
All observations are welcome :)

### CODE REVIEW

**Comment by tptee** [comment]
Thanks for this! I'll be looking at this soon.

You might want to consider this PR going in soon: https://github.com/FormidableLabs/redux-little-router/pull/73

It changes the store enhancer implementation a good bit. Might be a good reference for updating this PR when it lands!

**Comment by gavindoughtie** [comment]
FYI:

https://github.com/reactjs/react-router-redux#what-if-i-use-immutablejs-with-my-redux-store

You can pass selectLocationState as an override function in the options and use it to update immutable.

**Comment by gavindoughtie** [comment]
Hey guys, I'd love to see this integrated. What can I do to help out?

**Comment by Nihaux** [comment]
a lot of the master code have changed since my PR, I will try to work on it based on the new code by the end of the week. But I close this PR as it's not good anymore.

**Comment by Nihaux** [comment]
@gavindoughtie https://github.com/FormidableLabs/redux-little-router/pull/119

**Pull request closed without merging**
