### PR TITLE
Add tests for nested fragments and default route.

### PR DESCRIPTION
**Pull request by mariusk**

### CODE REVIEW

**Comment by mariusk** [comment]
So just to be clear; I'm not even sure Fragment can be used similarily to Router from react-router. I just added the tests to highlight typical use-cases for people coming from react-router. Specifically if there is no mechanism to select the first matched Fragment from a list, each Fragment would have to exclude all the other possibilities. From the limited docs it seems the primary use-case for Fragment is to toggle components on and off rather than act as (react-router) Router. If so this is probably worth highlighting in the docs.

**Comment by mmcgahan** [comment]
I really like this project, but I think this PR highlights an important missing feature - the ability to order routes by priority so that overlapping URL patterns can be resolved predictably.

Looking at the source, I think [this](https://github.com/FormidableLabs/redux-little-router/blob/master/src/create-matcher.js#L68,L69) is the implicit prioritization of routes, based on reverse-alphabetical order of the route strings.

I'm wondering if it might make sense to move toward an explicit array-based `routes` definition so that route patterns could be tested in the order explicitly provided

**Comment by tptee** [comment]
You couldn't have had better timing: https://github.com/FormidableLabs/redux-little-router/pull/108

I'll be cutting a major release with this over the weekend 🎉

**Comment by tptee** [comment]
I guess I just never closed this? But greedy nested fragments and default routes are both available as of `v13`!

**Pull request closed without merging**
