### PR TITLE
Replace {} with any

### PR DESCRIPTION
**Pull request by NeoLegends**
Hey! I've got another bug in the TS typings that's waiting to be fixed. :)

`{}` does not represent a 'plain object' in TS. This leads to problems using `state.router.result.someProperty`, because TS asserts that `someProperty` doesn't exist, when in fact, it does. `any` is the right type to be used here.

### CODE REVIEW

**Comment by parkerziegler** [comment]
Good catch @NeoLegends! I'd still like to make some sort of contract saying that these need to be objects. Perhaps we could use `index` signatures, similar to how we do with the `Routes` interface? Let me know your thoughts on this. Something like:

```
interface ObjLiteral {
    [key: string]: any;
}
```

I've never been truly certain on how to deal with objects of unknown shape in TS. `any` is a great escape hatch if we need it, but would like to use something a bit safer if possible. Thanks!

**Comment by parkerziegler** [comment]
@NeoLegends this looks good to me, finally had some time to review and all seems to be going smoothly. Please pull latest from `master` into your branch and then push to this PR and I can merge. cc @ryan-roemer @tptee We can cut a patch release later this week to pull in these updated defs.

**Comment by tptee** [comment]
🚢

**Comment by NeoLegends** [comment]
🤟🏻

**Comment by davidgruar** [comment]
@parkerziegler @ryan-roemer @tptee Any chance of getting this released, please?

**Comment by parkerziegler** [comment]
Thanks for pinging us @davidgruar! Meant to cut another release after these got merged but forgot.

@ryan-roemer @tptee I'm happy to cut a new release later today, how do we want to do versioning (major/minor/patch). IIRC, the diff is just changes to TS defs.

**Comment by parkerziegler** [comment]
@davidgruar [v15.1.1](https://github.com/FormidableLabs/redux-little-router/releases/tag/v15.1.1) is published to `npm`. Let us know if you encounter anything funny!

**Comment by davidgruar** [comment]
Thank you! It would be worth mentioning #280 in the release notes - it resolves the same issue as #282 but for Typescript (and is actually what I most needed this release for).

**Comment by parkerziegler** [comment]
Good call out, it's been added!

**Pull request merged**
